package io.wyrmise.hanusync.adapters;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.TextView;

import java.util.ArrayList;

import io.wyrmise.hanusync.R;
import io.wyrmise.hanusync.objects.Grade;

/**
 * Created by Demise on 5/19/2015.
 */
public class GradeAdapter extends ArrayAdapter<Grade> {
    public ArrayList<Grade> gradeArrayList;
    Holder holder;
    private Context ctx;

    /**
     * @param context
     * @param textViewResourceId
     * @param messageListArray
     * @overview constructor method inherited from ArrayAdapter
     */
    public GradeAdapter(Context context, int textViewResourceId,
                        ArrayList<Grade> messageListArray) {
        super(context, textViewResourceId);
        this.gradeArrayList = messageListArray;
        this.ctx = context;
    }

    @Override
    public int getViewTypeCount() {
        if (getCount() != 0)
            return getCount();
        return 1;
    }

    /**
     * @effect get the View generated by the current instance of MessageAdapter
     */
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        View convertView1 = convertView;
        LayoutInflater vi = (LayoutInflater) ctx
                .getSystemService(Context.LAYOUT_INFLATER_SERVICE);

        if (convertView1 == null) {
            holder = new Holder();
            convertView1 = vi.inflate(R.layout.table_row, parent,
                    false);
            holder.name = (TextView) convertView1
                    .findViewById(R.id.grade_item);
            holder.grade = (TextView) convertView1
                    .findViewById(R.id.grade);
            holder.percentage = (TextView) convertView1.findViewById(R.id.percentage);
            convertView1.setTag(holder);
        } else {
            holder = (Holder) convertView1.getTag();
        }
        Grade row = getItem(position);

        holder.name.setText(row.name);
        holder.grade.setText(row.grade);
        holder.percentage.setText(row.percentage);

        return convertView1;
    }

    /**
     * @effects returns the size of the array of adapter
     */
    @Override
    public int getCount() {
        return gradeArrayList.size();
    }

    /**
     * @effects returns the item at specific position
     */
    @Override
    public Grade getItem(int position) {
        return gradeArrayList.get(position);
    }

    /**
     * @author wyrmise
     * @overview class to hold the references of the TextViews used in ListView
     */
    private class Holder {
        public TextView name, grade, percentage;
    }

}
